### ISSUE TITLE
ArgumentError from load_additional_types

### ISSUE THREAD

**Issue by AnthonyDeSimone** [crashtech/torque-postgresql#20]
With the gem installed, every AR query generates this error:

```
ArgumentError: wrong number of arguments (given 0, expected 1..2)
from /home/anthony/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/torque-postgresql-0.2.7/lib/torque/postgresql/adapter/database_statements.rb:42:in `load_additional_types'
```
I'm using:
Rails version 5.2.0.rc2
PG version 1.0.0

**Comment by mlt** [comment]
Current version isn't compatible with Rails 5.2. You may give a try to my [PR](/crashtech/torque-postgresql/issues/21) (WIP). Although I did not test with Rails 5.2.0 and all checks in the code compare with 5.2.1.

**Comment by crashtech** [comment]
@AnthonyDeSimone I have just deployed a new version supporting Rails 5.2.1, can you give it a try?

**Comment by crashtech** [comment]
@AnthonyDeSimone I have just deployed a new version supporting Rails 5.2.1, can you give it a try?
