### ISSUE TITLE
enum.base_method configuration has no effect

### ISSUE THREAD

**Issue by subtletech** [crashtech/torque-postgresql#25]
I'm on Rails 5.2 and I have ActiveRecord's featured enums in some models. Thus `torque-postgresql` breaks the code by bringing it's own `enum` class method into ActiveRecord::Base.

Have tried to alter the method name as stated in the docs by placing the following code into `application.rb`:
```
Torque::PostgreSQL.configure do |c|
  c.enum.base_method = :pg_enum
end
```
Which seems to have no effect.

From what I understand, all components of `Torque::PostgreSQL` are require'ed on gem loading, including `Torque::PostgreSQL::Attributes::Enum::Base`, which body is evaluated resulting in the definition of the conflicting `enum` method -- all of that happens BEFORE the configuration statement I've put into `application.rb` is executed.

I've resorted to a kinda dirty fix by just removing the method:
```
Torque::PostgreSQL::Attributes::Enum::Base.module_eval do
  remove_method :enum
end
```

I have `torque-postgresql (0.2.13)` in Gemfile.lock.

**Comment by crashtech** [comment]
Thanks for reporting this! I'm gonna push a fix later today.
