### ISSUE TITLE
ActiveSupport::Duration::ISO8601Parser::ParsingError when working with interval fields under certain curcumstances

### ISSUE THREAD

**Issue by subtletech** [crashtech/torque-postgresql#26]
Steps to reproduce:
1. Have an ActiveRecord model with an interval field. Let's say `Event` and `duration`.
2. Invoke statements:
```
event = Event.find(1)
event.update(duration: ActiveSupport::Duration.build(1000000)) # 1000000 is just a large number of seconds
event.duration
```
The last statement `event.duration` chokes with an `ActiveSupport::Duration::ISO8601Parser::ParsingError` exception with message like `Invalid ISO 8601 duration: "P1W4DT13H46M40S" mixing weeks with other date parts not allowed`.

Reason: `ActiveSupport::Duration.build` assings the `weeks` field of the `Duration` instance, then such a value during `#update` gets incorrectly serialized in `Torque::PostgreSQL::Adapter::OID::Interval#serialize` to a string like `P1W4DT13H46M40S`. After `#update` on access to the field, the value tries to deserialize from such a string and `ISO8601Parser` actually does care of the format correctness.

Possible fix: sanitize `ActiveSupport::Duration` values somehow in `Torque::PostgreSQL::Adapter::OID::Interval#cast`

**Comment by crashtech** [comment]
I opened an [issue on Rails GEM](https://github.com/rails/rails/issues/34655), but I'm also fixing this on the GEM for the next version!
Thanks for reporting this!
