### ISSUE TITLE
Array associations bug

### ISSUE THREAD

**Issue by rainerborene** [crashtech/torque-postgresql#40]
Say we need to remove an existing association from a `video_ids` array column like this:
```ruby
class Video < ActiveRecord::Base
  has_many :tags, array: true
end

class Tag < ActiveRecord::Base
  belongs_to_many :videos
end

video = Video.first
video2 = Video.last

tag = Tag.first
tag.video_ids = [video.id, video2.id]
tag.save!

video.tags.clear # BOOM! 💣 

video2.tags.empty? # THIS WILL BE TRUE!
```
That should not be the expected behavior, right?

**Comment by crashtech** [comment]
Well, the behavior seems correct. Maybe changing the architecture would it behave properly:
```ruby
class Video < ActiveRecord::Base
  belongs_to_many :tags
end

class Tag < ActiveRecord::Base
  has_many :videos, array: true
end
```

This for me makes more sense and would fix your issue.

**Comment by crashtech** [comment]
@rainerborene Were you able to solve the problem? Can I help in any other way?
