### ISSUE TITLE
Doesn’t work with Rails 6

### ISSUE THREAD

**Issue by marnen** [crashtech/torque-postgresql#41]
Just letting you know that this gem doesn’t work with Rails 6 yet, due to some major changes in the AR schema API. I’m working on updating it and will hopefully have a pull request fairly soon.

**Comment by crashtech** [comment]
Hey @marnen! Thanks for letting me know. If I can help in any way, if you need some guidance, just let me know.

**Comment by marnen** [comment]
Thanks! The change in API has made this a bit of a drag, but I’ll be back in touch with you with questions when I have more time to spend on it.

**Comment by crashtech** [comment]
@marnen I just released a new version, which might not affect your changes, unless most of them are related to array associations. Let me know how I can help, even if it's just for some guidance.

**Comment by marnen** [comment]
Thanks for the update. I need to get back to working on this, if I even bother. I’m only using Torque for duration support, so it may not be worth it for me, but OTOH I do want Torque to be available for Rails 6 projects and no one else seems to be making that happen.

**Comment by crashtech** [comment]
I think that's a good idea, and I can also help you to do the fixes for Rails 6. I was thinking that maybe event creating the `v2.0.0` exclusively for Rails 6+, removing backward compatibility (but maintaining both versions 1 and 2, for a while).

Just a question, any reason why not use the other features available? I have a bunch of other features that I want to add, but not quite sure which one to pursue. Maybe the recursive CTEs.

**Comment by marnen** [comment]
> I was thinking that maybe event creating the v2.0.0 exclusively for Rails 6+, removing backward compatibility 

Yes, that may have to happen. There are some fairly big changes in ActiveRecord 6.

> any reason why not use the other features available?

So far I haven't needed them for anything I'm doing. Also, I only recently found out about this gem in the first place. :)

**Comment by crashtech** [comment]
I might start some work towards Rails 6 in the next days (a new project came up, so it would be ideal to have the GEM in this project which uses Rails 6). Let me know if you can share what you have.

**Comment by marnen** [comment]
Sure. I’ll try to do that over Christmas. Thanks for the reminder. 

(BTW: it’s “gem”, not “GEM”. It’s an ordinary English word, not an acronym. :) )

**Comment by marnen** [comment]
I just pushed my work at https://github.com/marnen/torque-postgresql/tree/rails-6-wip. Enjoy!

**Comment by crashtech** [comment]
The new version 2 now works on Rails 6.
