### ISSUE TITLE
Error trying to associate records to a new model

### ISSUE THREAD

**Issue by smarquez1** [crashtech/torque-postgresql#43]
When I try to associate records to a new mode, I get the following ActiveRecord error:

```ruby
> tag = FactoryBot.create(:tag)
> Video.new tags: [tag]

 ActiveRecord::ActiveRecordError:
       cannot update a new record
```
I think that the following line is the culprit, since it tries to update the record without knowing if it's already persisted: https://github.com/crashtech/torque-postgresql/blob/master/lib/torque/postgresql/associations/belongs_to_many_association.rb#L36

**Comment by crashtech** [comment]
Thank you for finding this problem and sending a PR
I'll add a new version with this fix
