### ISSUE TITLE
Prepared statement bug?

### ISSUE THREAD

**Issue by sigra** [crashtech/torque-postgresql#48]
Hi. I faced with very annoying bug. Let's assume we have the following structure:

```ruby
    create_table :products do |t|
      t.string :name
      t.integer :code_ids, array: true
    end

    create_table :codes do |t|
      t.string :name
    end
```

And simple models with simple relations:

```ruby
class Product < ApplicationRecord; belongs_to_many :codes ;end
class Code < ApplicationRecord; has_many :products, array: true; end
```

Let's prepare some data:

```ruby
code_ids = Code.pluck(:id)

# create Product with 1 Code (it's important to be first)
Product.create(name: 'one code', code_ids: code_ids.sample)

# create Product with 5 Codes
Product.create(name: 'five codes', code_ids.sample(5))
```

Now, let's play with collection where first Product has one Code:

```ruby
Product.order(id: :asc).each do |product|
  puts product.codes.map(&:name).to_sentence
end
```

In the output both Products will have just one Code, but second Product should have 5:
```
  Product Load (2.8ms)  SELECT "products".* FROM "products" ORDER BY "products"."id" ASC
  Code Load (0.5ms)  SELECT "codes".* FROM "codes" WHERE "codes"."id" IN ($1)  [["code_ids", 169]]
F-1981
  Code Load (0.4ms)  SELECT "codes".* FROM "codes" WHERE "codes"."id" IN ($1)  [["code_ids", 856]]
Q88
```

Go ahead and reload our server to clear cache and do vice versa experiment :)

```ruby
Product.order(id: :desc).each do |product|
  puts product.codes.map(&:name).to_sentence
end
```

Now output seems to be fine, but relation still uses cached prepared statement and puts `NULL` in sql:
```
Product Load (0.3ms)  SELECT "products".* FROM "products" ORDER BY "products"."id" DESC
  Code Load (0.4ms)  SELECT "codes".* FROM "codes" WHERE "codes"."id" IN ($1, $2, $3, $4, $5)  
[["code_ids", 564], ["code_ids", 947], ["code_ids", 546], ["code_ids", 888], ["code_ids", 473]]
B54, VN-9122, O-2587, N-8840, X23

Code Load (0.2ms)  SELECT "codes".* FROM "codes" WHERE "codes"."id" IN ($1, $2, $3, $4, $5)  
[["code_ids", 169], ["code_ids", nil], ["code_ids", nil], ["code_ids", nil], ["code_ids", nil]]
F-1981
``` 

Any ideas how to fix this?

—————

My Gemfile:
```
ruby '2.5.6'

gem 'torque-postgresql', '~> 1.1'
gem 'pg', '= 1.2.3'
gem 'rails', '= 5.2.4.3'
```

**Comment by sigra** [comment]
https://github.com/rails/rails/blob/5-2-stable/activerecord/lib/active_record/reflection.rb#L441

Seems that it is very logical Rails behavior. `@association_scope_cache` is created just once because it is fair for typical `has_many` relation where our query always looks like `SELECT * FROM products WHERE products.code_id = $1`.

In the case of this gem query strictly depends on the array size of foreign column and we should create new `key` for each possible array size. 

Sounds like an easy fix but let's imagine if we have 1,000 different array sizes which produce 1,000 prepared statements... Do we really need statement caching here?

**Comment by sigra** [comment]
So, the approach how to fix this is redefine original method `find_target` from `ActiveRecord::Associations::CollectionAssociation` https://github.com/rails/rails/blob/5-2-stable/activerecord/lib/active_record/associations/collection_association.rb#L304

Original:

```ruby
def find_target
  scope = self.scope
  return scope.to_a if skip_statement_cache?(scope)

  conn = klass.connection
  sc = reflection.association_scope_cache(conn, owner) do |params|
    as = AssociationScope.create { params.bind }
    target_scope.merge!(as.scope(self))
  end
  binds = AssociationScope.get_bind_values(owner, reflection.chain)
  sc.execute(binds, conn) do |record|
    set_inverse_instance(record)
  end
end
```

Just remove all lines that related to statement cache and put this into `Torque::PostgreSQL::Associations::BelongsToManyAssociation`:
 
```ruby
def find_target
  self.scope.to_a
end
```

**Comment by LinchSmyth** [comment]
I solved this issue in different way using `Associations::Association`:

```
def skip_statement_cache?(scope)
  super(scope) || reflection.connected_through_array?
end
```

I wonder why something like this aren't in gem already.

**Comment by crashtech** [comment]
Hi @sigra. The param bidding is actually a feature from the `pg` gem, Rails only prepares the statements to use it. Since `IN` is not an actual array, the binding could not be done as `IN $1`. That said, the easy solution from now seems to be what @LinchSmyth mentioned.

This was not implemented in this gem because where I use it we try to keep "one query per table" in any process, which pretty much ended up not using cached statements. However, I will be spending some time thinking about this.

**Comment by crashtech** [comment]
Do you need this fix for Rails 5 as well?

**Comment by kbrock** [comment]
is it safe to close this? Rails 5.2.x is security update only? @sigra are you using rails 5.x?

**Comment by crashtech** [comment]
Yes, I'm mainly keeping 5.x on security updates. But if someone needs fixes or anything I can add them there.

**Comment by sigra** [comment]
> is it safe to close this? Rails 5.2.x is security update only? @sigra are you using rails 5.x?

A lot of people are still using Rails 5 because of hard legacy dependencies, monkey-patches and etc. So, I suppose this fix should be applied for Rails 5 too, especially it's not a big fix.

Anyway, our company has forked this gem and applied several fixes needed for us including this one. So, this issue can be closed. Anyone who faces with this issue can easily create a fork and apply [fix](https://github.com/crashtech/torque-postgresql/issues/48#issuecomment-706073407)

**Comment by crashtech** [comment]
@sigra Just pushed this fix. Let me know how I can help you and your company to use the gem without the fork. Maybe we can join forces using the main repo.
