### ISSUE TITLE
belongs_to_many: associated relations are removed

### ISSUE THREAD

**Issue by yosiat** [crashtech/torque-postgresql#54]
Hi!

I am trying out this gem, with `belongs_to_many` on rails 6.1, running my tests I found a bug which causes relations to be removed.

Once:

- I have a `before_save` callback which does `.count`
- ..and I do `#update` to update another column

The associated relations are removed, with the script below `test_sanity_with_callback` will fail
Both on rails 6.1 and 6.0

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.1.0"
  gem "torque-postgresql"
  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(
  adapter:  "postgresql",
  database: "test",
  encoding: "unicode",
  host:     "localhost",
  port:     "5432",
  password: "12345",
  username: "test")

ActiveRecord::Schema.define do
  drop_table "employees"
  drop_table "projects"

  create_table "employees" do |t|
    t.string "name"
    t.timestamps
  end

  create_table "projects" do |t|
    t.bigint "employees_ids", array: true
    t.string "title"
    t.timestamps
  end
end

class Employee < ActiveRecord::Base
end

class Project < ActiveRecord::Base
  belongs_to_many :employees, foreign_key: :employees_ids

  before_save :check_count

  def check_count
    # NOTE: the `.count` here is important for the failure
    puts "Project#check_count - #{employees.count}"
  end
end


class BugTest < Minitest::Test
  def test_sanity
    # create project with employee
    employee = Employee.create!
    project = Project.create!
    project.employees << employee

    project.update(title: "new title")

    project.reload

    assert_equal 1, project.employees.count
    assert_equal 1, project.employees_ids.count
  end

  def test_sanity_with_callback
    # create project with employee
    employee = Employee.create!
    project = Project.create!
    project.employees << employee

    # NOTE
    #
    # Same as `test_sanity`, but here the difference is:
    # * I am doing `.reload`
    # * We have a callback
    #
    # Both of these will cause `update` to remove `employees_ids`
    #
    # happens because of: https://github.com/crashtech/torque-postgresql/blob/master/lib/torque/postgresql/autosave_association.rb#L38
    # Set `employees_ids` to empty array
    #
    project.reload

    project.update(title: "new title")

    assert_equal 1, project.employees.count
    assert_equal 1, project.employees_ids.count
  end
end
```

**Comment by yosiat** [comment]
I debugged this and tried to come up with a fix, the only thing that fixed it is changed this line:
https://github.com/crashtech/torque-postgresql/blob/master/lib/torque/postgresql/autosave_association.rb#L37

From: `records = association.target.each_with_object(klass_attr)`
To: `records = association.load_target.each_with_object(klass_attr)`

But I am not sure - why this bug happens and what should be the fix for it

**Comment by crashtech** [comment]
Thanks for finding this issue. In the end, the customized `autosave_association` was not needed because the manipulation of the ids column was being executed in another place. Just a recommendation, instead of using `"Project#check_count - #{employees.count}"`, just use "Project#check_count - #{employees_ids.size}" which will give you the same result without performing another query.

**Comment by yosiat** [comment]
@crashtech thanks for the fix!

About the recommendation, totally agree! I am trying to get my project working with this new association type, and then I'll do round of optimizations :)
