### ISSUE TITLE
Belongs To Many with custom foreign key

### ISSUE THREAD

**Issue by lasseebert** [crashtech/torque-postgresql#91]
I have tried using this gem and `belongs_to_many` for the first time.

In my case I want to use it on a non-default primary key (`short_id` instead of `id`), so I define it like this:

```ruby
belongs_to_many :tags, primary_key: :short_id, foreign_key: :tag_short_ids
```

This works fine, e.g. when using preload and calling `tags` on my model. However, if I try to set the tags with `tags=`, it uses the `id` column of the tags instead of the `short_id`.

On another note: I think there is a mistake in [the wiki page for belongs_to_many](https://github.com/crashtech/torque-postgresql/wiki/Belongs-to-Many) where the descriptions for `primary_key` and `foreign_key` seems to be swapped in the options section.

Thanks for an awesome gem!

**Comment by lasseebert** [comment]
Thanks for fixing so fast @crashtech 

I had some incompatibility issues with some of our own ActiveRecord tweaks (I think), but I will try this gem again soon and see if I can make it work.

**Comment by crashtech** [comment]
Sure! Let me know if I can help in any way.
